id: I3AA785A5
legacy_id: P007927
ocr_import_info:
  bdrc_scan_id: W3CN3333
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T18:57:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:33:56.197831+00:00'
last_modified: 2022-09-03 21:34:52.749648
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3333
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3333
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སེ་ར་ཡང་སྤྲུལ་གྱི་གསུང་འབུམ།
  author: སེ་ར་ཡང་སྤྲུལ།
statistics:
  ocr_word_mean_confidence_index: 0.4920975296513021
  ocr_word_median_confidence_index: 0.46000000834465027
quality: null
bases:
  I3CN3576:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3576
      total_pages: 374
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3CN3576.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.512368747599379
    legacy_id: v007
  I3CN3571:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3571
      total_pages: 544
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN3571.txt
    statistics:
      ocr_word_median_confidence_index: 0.4399999976158142
      ocr_word_mean_confidence_index: 0.4687740190280466
    legacy_id: v002
  I3CN3577:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3577
      total_pages: 150
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3CN3577.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5251578467836941
    legacy_id: v008
  I3CN3575:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3575
      total_pages: 506
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3CN3575.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.49904062194410026
    legacy_id: v006
  I3CN3573:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3573
      total_pages: 282
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN3573.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.4987512398268639
    legacy_id: v004
  I3CN3574:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3574
      total_pages: 478
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN3574.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5194140165033068
    legacy_id: v005
  I3CN3572:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3572
      total_pages: 454
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN3572.txt
    statistics:
      ocr_word_median_confidence_index: 0.41999998688697815
      ocr_word_mean_confidence_index: 0.46108011288604367
    legacy_id: v003
  I3CN3570:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3570
      total_pages: 254
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3570.txt
    statistics:
      ocr_word_median_confidence_index: 0.4399999976158142
      ocr_word_mean_confidence_index: 0.46856278945727114
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
