id: P007927
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3333
  title: སེ་ར་ཡང་སྤྲུལ་གྱི་གསུང་འབུམ།
  author: ''
  volumes:
    ad6ab8bd5caf45b28a393999512d9081:
      image_group_id: I3CN3570
      title: ''
      volume_number: 1
      total_pages: 254
    728ec81da1b643a89966eba1e5b079fb:
      image_group_id: I3CN3571
      title: ''
      volume_number: 2
      total_pages: 544
    46bd1567287c4a06836cf0fa22c1f236:
      image_group_id: I3CN3572
      title: ''
      volume_number: 3
      total_pages: 454
    119f129000e24b628d79cb3d228c173a:
      image_group_id: I3CN3573
      title: ''
      volume_number: 4
      total_pages: 282
    7d04f2f828fc431abe1131af06d9d10d:
      image_group_id: I3CN3574
      title: ''
      volume_number: 5
      total_pages: 478
    12af5bcc9b574a25853f258e9ad70951:
      image_group_id: I3CN3575
      title: ''
      volume_number: 6
      total_pages: 506
    a11c6087e6c3425e8fb19421c4ccbf28:
      image_group_id: I3CN3576
      title: ''
      volume_number: 7
      total_pages: 374
    2cad090ea38b418eb8c3652ea8e35581:
      image_group_id: I3CN3577
      title: ''
      volume_number: 8
      total_pages: 150
ebook_metadata:
  title: སེ་ར་ཡང་སྤྲུལ་གྱི་གསུང་འབུམ།
  author: ''
  sku: P007927
  cover: cover.jpg
  layers:
  - pagination
